export const projects = [
   {
      title: 'E-commerce Website',
      description: `A fully website for a local business that can sells products online with a payment system and a dashboard for the admin to manage the products and orders.`,
      img: '/E-Commerce.png',
      href: 'https://market-app-next-ts.vercel.app/',
      alt: 'Projects',
      delay: 0.1,
   },
   {
      title: 'Complete Design System',
      description: `A complete design system for a website that can be used for any website with a dark and light theme and a lot of components premade.`,
      img: '/Design-System.png',
      href: 'https://market-app-next-ts.vercel.app/',
      alt: 'Projects',
      delay: 0.2,
   },
   {
      title: 'Dashboard Template',
      description: `A dashboard template for a website that can be used for any website that needs a dashboard.`,
      img: '/Dashboard.png',
      href: 'https://maze-app-two.vercel.app/',
      alt: 'Projects 1',
      delay: 0.3,
   },
   {
      title: 'Landing Page Template',
      description: `Landing page for any SaaS company.`,
      img: '/Landing.png',
      href: 'https://maze-app-two.vercel.app/',
      alt: 'Projects 1',
      delay: 0.3,
   },
   {
      title: 'Crow Founding System with smart contracts',
      description: `Campagin system for a crow founding system using blockchain system.`,
      img: '/Funding.png',
      href: 'https://maze-app-two.vercel.app/',
      alt: 'Projects 1',
      delay: 0.3,
   },
   {
      title: 'Lottery Random System with smart contracts',
      description: `Lottery system using blockchain system, that takes the money from the players and gives it to a random player.`,
      img: '/Lottery.png',
      href: 'https://maze-app-two.vercel.app/',
      alt: 'Projects 1',
      delay: 0.3,
   },
   {
      title: 'Portfolio Website',
      description: `My portfolio website that you are currently on.`,
      img: '/Portfolio-2.png',
      href: 'https://maze-app-two.vercel.app/',
      alt: 'Projects 1',
      delay: 0.3,
   },
   {
      title: 'Portfolio Template',
      description: `Simple and minimalist portfolio with dark mode support and more than 25 themes.`,
      img: '/Portfolio.png',
      href: 'https://maze-app-two.vercel.app/',
      alt: 'Projects 1',
      delay: 0.3,
   },
   {
      title: 'Maze Rat Game',
      description: `Maze rat solver game using the A*, Prism algorithm to find the shortest path between the rat and the cheese.`,
      img: '/Maze-Rat.png',
      href: 'https://maze-app-two.vercel.app/',
      alt: 'Projects 1',
      delay: 0.3,
   },
   {
      title: 'Visual Generator App',
      description: `Visual editor with a drag and drop system that can generate python code.`,
      img: '/Drawflow-Sentences.png',
      href: 'https://maze-app-two.vercel.app/',
      alt: 'Projects 1',
      delay: 0.3,
   },
   {
      title: 'Gif App',
      description:
         'A gif app that can search for gifs and save them in a favorites section.',
      img: '/Gif-App.png',
      href: '',
      alt: 'Projects 2',
      delay: 0.3,
   },
   {
      title: 'Heroes App',
      description: `A website that can search for heroes and see their information.`,
      img: '/Heroes-App.png',
      href: '',
      alt: 'Projects 2',
      delay: 0.3,
   },
   {
      title: 'Tailwind Auto Applier Prefixer',
      description:
         'Web application to apply any prefix to existing file what uses Tailwind CSS.',
      img: '/Prefixer.png',
      href: '',
      alt: 'Projects 2',
      delay: 0.3,
   },
];
