export const projects = [
  {
    title: "Design System TailwindCSS (Ripple UI)",
    description: `A complete design system for a website that can be used for any website with a dark and light theme and a lot of components premade based TailwindCSS.`,
    img: "/RippleUI.png",
    href: "/projects/ecommerce",
    preview: "https://www.ripple-ui.com/",
    github: "https://github.com/Siumauricio/rippleui",
    alt: "Projects",
    platform: "Web",
    stack: "TailwindCSS, Nextjs, Typescript, CSS.",
    delay: 0.1,
  },
  {
    title: "E-commerce Website",
    description: `A fully website for a local business that can sells products online with a payment system and a dashboard for the admin to manage the products and orders.`,
    img: "/E-Commerce.png",
    href: "/projects/ecommerce",
    preview: "https://market-app-next-ts.vercel.app/",
    github: "https://github.com/Siumauricio/zorotek",
    alt: "Projects",
    platform: "Web",
    stack: "NextJS, Redux Toolkit, Typescript, TailwindCSS, Cloudinary.",
    delay: 0.1,
  },
  {
    title: "Complete Design System",
    description: `A complete design system, support for SSR, dark and light mode included for React and Nextjs applications.`,
    img: "/Design-System.png",
    href: "/projects/design-system",
    preview: "https://ripple-ui.vercel.app/docs/get-started/installation",
    github: "https://github.com/Siumauricio/ripple-ui",
    alt: "Projects",
    platform: "Web",
    stack: "Typescript, React, Stitches.",
    delay: 0.2,
  },
  {
    title: "Dashboard Template",
    description: `A dashboard template for a website that can be used for any website that needs a dashboard.`,
    img: "/Dashboard.png",
    href: "/projects/dashboard",
    preview: "https://nextui-dashboard-template.vercel.app/",
    github: "https://github.com/Siumauricio/nextui-dashboard-template",
    platform: "Web",
    stack: "Typescript, Nextjs, NextUI.",
    alt: "Projects 1",
    delay: 0.3,
  },
  {
    title: "Landing Page Template",
    description: `Landing page for any SaaS company.`,
    img: "/Landing.png",
    href: "/projects/landing",
    preview: "https://landing-template-nextui.vercel.app/",
    github: "https://github.com/Siumauricio/landing-template-nextui",
    platform: "Web",
    stack: "Typescript, Nextjs, NextUI.",
    alt: "Projects 1",
    delay: 0.3,
  },
  {
    title: "Crow Founding System with smart contracts",
    description: `Campagin system for a crow founding system using blockchain system.`,
    img: "/Funding.png",
    href: "/projects/funding",
    preview: "https://campaign-frontend.vercel.app/",
    github: "https://github.com/Siumauricio/campaign-frontend",
    platform: "Web",
    stack: "Typescript, Nextjs, Ripple UI, Solidity, Blockchain, NodeJS.",
    alt: "Projects 1",
    delay: 0.3,
  },
  {
    title: "Checkers Game",
    description: `A traditional checkers game with drag and drop functionality.`,
    img: "/Checkers.png",
    href: "/projects/checkers",
    preview: "https://checkers-game-five.vercel.app/",
    github: "https://github.com/Siumauricio/checkers-game",
    platform: "Web",
    stack: "Typescript, Nextjs, Next UI.",
    alt: "Projects 1",
    delay: 0.3,
  },
  {
    title: "Lottery Random System with smart contracts",
    description: `Lottery system using blockchain system, that takes the money from the players and gives it to a random player.`,
    img: "/Lottery.png",
    href: "/projects/lottery",
    preview: "https://lottery-frontend-ochre.vercel.app/",
    github: "https://github.com/Siumauricio/lottery-frontend",
    platform: "Web",
    stack: "Typescript, ReactJS, Ripple UI, Solidity, Blockchain, NodeJS.",
    alt: "Projects 1",
    delay: 0.3,
  },
  {
    title: "Portfolio Website",
    description: `My portfolio website that you are currently on.`,
    img: "/Portfolio-2.png",
    href: "/projects/portfolio",
    preview: "https://portfolio-de3p.vercel.app/",
    github: "https://github.com/Siumauricio/portfolio",
    platform: "Web",
    stack: "Typescript, Nextjs, NextUI.",
    alt: "Projects 1",
    delay: 0.3,
  },
  {
    title: "Portfolio Template",
    description: `Simple and minimalist portfolio with dark mode support and more than 25 themes.`,
    img: "/Portfolio.png",
    href: "/projects/portfolio-template",
    preview: "https://my-portfolio-swart-chi.vercel.app/",
    github: "https://github.com/Siumauricio/nextjs-template-portfolio",
    platform: "Web",
    stack: "Typescript, Nextjs, DaisyUI, TailwindCSS.",
    alt: "Projects 1",
    delay: 0.3,
  },
  {
    title: "Maze Rat Game",
    description: `Maze rat solver game using the A*, Prism algorithm to find the shortest path between the rat and the cheese.`,
    img: "/Maze-Rat.png",
    href: "/projects/maze-rat",
    preview: "https://maze-app-two.vercel.app/",
    github: "https://github.com/Siumauricio/Maze-App",
    platform: "Web",
    stack: "Javascript, React, Bootstrap.",
    alt: "Projects 1",
    delay: 0.3,
  },
  {
    title: "Visual Generator App",
    description: `Visual editor with a drag and drop system that can generate python code.`,
    img: "/Drawflow-Sentences.png",
    href: "/projects/visual-generator",
    preview: "https://draw-flow-sentences.vercel.app/",
    github: "https://github.com/Siumauricio/DrawFlow-Sentences",
    platform: "Web",
    stack: "Vue, Bootstrap.",
    alt: "Projects 1",
    delay: 0.3,
  },
  {
    title: "Gif App",
    description:
      "A gif app that can search for gifs and save them in a favorites section.",
    img: "/Gif-App.png",
    href: "/projects/gif-app",
    preview: "https://siumauricio.github.io/GifApp/",
    github: "https://github.com/Siumauricio/GifApp",
    platform: "Web",
    stack: "Javascript, React, Bootstrap.",
    alt: "Projects 2",
    delay: 0.3,
  },
  {
    title: "Heroes App",
    description: `A website that can search for heroes and see their information.`,
    img: "/Heroes-App.png",
    href: "/projects/heroes-app",
    preview: "https://heroes-app-six-sable.vercel.app/marvel",
    github: "https://github.com/Siumauricio/Heroes-App",
    platform: "Web",
    stack: "Javascript, React, Bootstrap.",
    alt: "Projects 2",
    delay: 0.3,
  },
  {
    title: "Tailwind Auto Applier Prefixer",
    description:
      "Web application to apply any prefix to existing file what uses Tailwind CSS.",
    img: "/Prefixer.png",
    href: "/projects/prefixer",
    preview: "https://tailwind-autoprefixer-applier-files.netlify.app/",
    github:
      "https://github.com/Siumauricio/Tailwind-AutoPrefix-Applicator-Files",
    platform: "Web",
    stack: "Javascript, React, Bootstrap, NodeJS.",
    alt: "Projects 2",
    delay: 0.3,
  },
];
